micronaut:
  application:
    name: some-service
endpoints:
  health:
    enabled: true
#spring:
#  devtools:
#    restart:
#      enabled: false
#    livereload:
#      enabled: false
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    hikari:
#      poolName: Hikari
#      auto-commit: false
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
#    h2:
#      console:
#        enabled: false